
// We are modularizing this manually because the current modularize setting in Emscripten has some issues:
// https://github.com/kripken/emscripten/issues/5820
// In addition, When you use emcc's modularization, it still expects to export a global object called `Module`,
// which is able to be used/called before the WASM is loaded.
// The modularization below exports a promise that loads and resolves to the actual sql.js module.
// That way, this module can't be used before the WASM is finished loading.

// We are going to define a function that a user will call to start loading initializing our Sql.js library
// However, that function might be called multiple times, and on subsequent calls, we don't actually want it to instantiate a new instance of the Module
// Instead, we want to return the previously loaded module

// TODO: Make this not declare a global if used in the browser
var initSqlJsPromise = undefined;

var initSqlJs = function (moduleConfig) {

    if (initSqlJsPromise){
      return initSqlJsPromise;
    }
    // If we're here, we've never called this function before
    initSqlJsPromise = new Promise(function (resolveModule, reject) {

        // We are modularizing this manually because the current modularize setting in Emscripten has some issues:
        // https://github.com/kripken/emscripten/issues/5820

        // The way to affect the loading of emcc compiled modules is to create a variable called `Module` and add
        // properties to it, like `preRun`, `postRun`, etc
        // We are using that to get notified when the WASM has finished loading.
        // Only then will we return our promise

        // If they passed in a moduleConfig object, use that
        // Otherwise, initialize Module to the empty object
        var Module = typeof moduleConfig !== 'undefined' ? moduleConfig : {};

        // EMCC only allows for a single onAbort function (not an array of functions)
        // So if the user defined their own onAbort function, we remember it and call it
        var originalOnAbortFunction = Module['onAbort'];
        Module['onAbort'] = function (errorThatCausedAbort) {
            reject(new Error(errorThatCausedAbort));
            if (originalOnAbortFunction){
              originalOnAbortFunction(errorThatCausedAbort);
            }
        };

        Module['postRun'] = Module['postRun'] || [];
        Module['postRun'].push(function () {
            // When Emscripted calls postRun, this promise resolves with the built Module
            resolveModule(Module);
        });

        // There is a section of code in the emcc-generated code below that looks like this:
        // (Note that this is lowercase `module`)
        // if (typeof module !== 'undefined') {
        //     module['exports'] = Module;
        // }
        // When that runs, it's going to overwrite our own modularization export efforts in shell-post.js!
        // The only way to tell emcc not to emit it is to pass the MODULARIZE=1 or MODULARIZE_INSTANCE=1 flags,
        // but that carries with it additional unnecessary baggage/bugs we don't want either.
        // So, we have three options:
        // 1) We undefine `module`
        // 2) We remember what `module['exports']` was at the beginning of this function and we restore it later
        // 3) We write a script to remove those lines of code as part of the Make process.
        //
        // Since those are the only lines of code that care about module, we will undefine it. It's the most straightforward
        // of the options, and has the side effect of reducing emcc's efforts to modify the module if its output were to change in the future.
        // That's a nice side effect since we're handling the modularization efforts ourselves
        module = undefined;

        // The emcc-generated code and shell-post.js code goes below,
        // meaning that all of it runs inside of this promise. If anything throws an exception, our promise will abort
var k;k||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;
k.onRuntimeInitialized=function(){function a(f,l){switch(typeof l){case "boolean":cc(f,l?1:0);break;case "number":dc(f,l);break;case "string":ec(f,l,-1,-1);break;case "object":if(null===l)lb(f);else if(null!=l.length){var n=da(l.length);m.set(l,n);fc(f,n,l.length,-1);ea(n)}else sa(f,"Wrong API use : tried to return a value of an unknown type ("+l+").",-1);break;default:lb(f)}}function b(f,l){for(var n=[],p=0;p<f;p+=1){var u=r(l+4*p,"i32"),w=gc(u);if(1===w||2===w)u=hc(u);else if(3===w)u=ic(u);else if(4===
w){w=u;u=jc(w);w=kc(w);for(var K=new Uint8Array(u),I=0;I<u;I+=1)K[I]=m[w+I];u=K}else u=null;n.push(u)}return n}function c(f,l){this.Pa=f;this.db=l;this.Na=1;this.mb=[]}function d(f,l){this.db=l;this.fb=fa(f);if(null===this.fb)throw Error("Unable to allocate memory for the SQL string");this.lb=this.fb;this.$a=this.sb=null}function e(f){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=f){var l=this.filename,n="/",p=l;n&&(n="string"==typeof n?n:ha(n),p=l?ia(n+"/"+l):n);l=ja(!0,!0);p=ka(p,
l);f&&("string"==typeof f&&(f=la(f)),f.subarray||(f=new Uint8Array(f)),ma(p,l|146),n=na(p,577),oa(n,f,0,f.length,0),pa(n),ma(p,l))}this.handleError(q(this.filename,g));this.db=r(g,"i32");pb(this.db);this.gb={};this.Ra={}}var g=y(4),h=k.cwrap,q=h("sqlite3_open","number",["string","number"]),v=h("sqlite3_close_v2","number",["number"]),t=h("sqlite3_exec","number",["number","string","number","number","number"]),x=h("sqlite3_changes","number",["number"]),D=h("sqlite3_prepare_v2","number",["number","string",
"number","number","number"]),qb=h("sqlite3_sql","string",["number"]),mc=h("sqlite3_normalized_sql","string",["number"]),rb=h("sqlite3_prepare_v2","number",["number","number","number","number","number"]),nc=h("sqlite3_bind_text","number",["number","number","number","number","number"]),sb=h("sqlite3_bind_blob","number",["number","number","number","number","number"]),oc=h("sqlite3_bind_double","number",["number","number","number"]),pc=h("sqlite3_bind_int","number",["number","number","number"]),qc=h("sqlite3_bind_parameter_index",
"number",["number","string"]),rc=h("sqlite3_step","number",["number"]),sc=h("sqlite3_errmsg","string",["number"]),tc=h("sqlite3_column_count","number",["number"]),uc=h("sqlite3_data_count","number",["number"]),vc=h("sqlite3_column_double","number",["number","number"]),tb=h("sqlite3_column_text","string",["number","number"]),wc=h("sqlite3_column_blob","number",["number","number"]),xc=h("sqlite3_column_bytes","number",["number","number"]),yc=h("sqlite3_column_type","number",["number","number"]),zc=
h("sqlite3_column_name","string",["number","number"]),Ac=h("sqlite3_reset","number",["number"]),Bc=h("sqlite3_clear_bindings","number",["number"]),Cc=h("sqlite3_finalize","number",["number"]),ub=h("sqlite3_create_function_v2","number","number string number number number number number number number".split(" ")),gc=h("sqlite3_value_type","number",["number"]),jc=h("sqlite3_value_bytes","number",["number"]),ic=h("sqlite3_value_text","string",["number"]),kc=h("sqlite3_value_blob","number",["number"]),
hc=h("sqlite3_value_double","number",["number"]),dc=h("sqlite3_result_double","",["number","number"]),lb=h("sqlite3_result_null","",["number"]),ec=h("sqlite3_result_text","",["number","string","number","number"]),fc=h("sqlite3_result_blob","",["number","number","number","number"]),cc=h("sqlite3_result_int","",["number","number"]),sa=h("sqlite3_result_error","",["number","string","number"]),vb=h("sqlite3_aggregate_context","number",["number","number"]),pb=h("RegisterExtensionFunctions","number",["number"]),
wb=h("sqlite3_update_hook","number",["number","number","number"]);c.prototype.bind=function(f){if(!this.Pa)throw"Statement closed";this.reset();return Array.isArray(f)?this.Gb(f):null!=f&&"object"===typeof f?this.Hb(f):!0};c.prototype.step=function(){if(!this.Pa)throw"Statement closed";this.Na=1;var f=rc(this.Pa);switch(f){case 100:return!0;case 101:return!1;default:throw this.db.handleError(f);}};c.prototype.Ab=function(f){null==f&&(f=this.Na,this.Na+=1);return vc(this.Pa,f)};c.prototype.Pb=function(f){null==
f&&(f=this.Na,this.Na+=1);f=tb(this.Pa,f);if("function"!==typeof BigInt)throw Error("BigInt is not supported");return BigInt(f)};c.prototype.Ub=function(f){null==f&&(f=this.Na,this.Na+=1);return tb(this.Pa,f)};c.prototype.getBlob=function(f){null==f&&(f=this.Na,this.Na+=1);var l=xc(this.Pa,f);f=wc(this.Pa,f);for(var n=new Uint8Array(l),p=0;p<l;p+=1)n[p]=m[f+p];return n};c.prototype.get=function(f,l){l=l||{};null!=f&&this.bind(f)&&this.step();f=[];for(var n=uc(this.Pa),p=0;p<n;p+=1)switch(yc(this.Pa,
p)){case 1:var u=l.useBigInt?this.Pb(p):this.Ab(p);f.push(u);break;case 2:f.push(this.Ab(p));break;case 3:f.push(this.Ub(p));break;case 4:f.push(this.getBlob(p));break;default:f.push(null)}return f};c.prototype.qb=function(){for(var f=[],l=tc(this.Pa),n=0;n<l;n+=1)f.push(zc(this.Pa,n));return f};c.prototype.zb=function(f,l){f=this.get(f,l);l=this.qb();for(var n={},p=0;p<l.length;p+=1)n[l[p]]=f[p];return n};c.prototype.Tb=function(){return qb(this.Pa)};c.prototype.Qb=function(){return mc(this.Pa)};
c.prototype.run=function(f){null!=f&&this.bind(f);this.step();return this.reset()};c.prototype.wb=function(f,l){null==l&&(l=this.Na,this.Na+=1);f=fa(f);this.mb.push(f);this.db.handleError(nc(this.Pa,l,f,-1,0))};c.prototype.Fb=function(f,l){null==l&&(l=this.Na,this.Na+=1);var n=da(f.length);m.set(f,n);this.mb.push(n);this.db.handleError(sb(this.Pa,l,n,f.length,0))};c.prototype.vb=function(f,l){null==l&&(l=this.Na,this.Na+=1);this.db.handleError((f===(f|0)?pc:oc)(this.Pa,l,f))};c.prototype.Ib=function(f){null==
f&&(f=this.Na,this.Na+=1);sb(this.Pa,f,0,0,0)};c.prototype.xb=function(f,l){null==l&&(l=this.Na,this.Na+=1);switch(typeof f){case "string":this.wb(f,l);return;case "number":this.vb(f,l);return;case "bigint":this.wb(f.toString(),l);return;case "boolean":this.vb(f+0,l);return;case "object":if(null===f){this.Ib(l);return}if(null!=f.length){this.Fb(f,l);return}}throw"Wrong API use : tried to bind a value of an unknown type ("+f+").";};c.prototype.Hb=function(f){var l=this;Object.keys(f).forEach(function(n){var p=
qc(l.Pa,n);0!==p&&l.xb(f[n],p)});return!0};c.prototype.Gb=function(f){for(var l=0;l<f.length;l+=1)this.xb(f[l],l+1);return!0};c.prototype.reset=function(){this.freemem();return 0===Bc(this.Pa)&&0===Ac(this.Pa)};c.prototype.freemem=function(){for(var f;void 0!==(f=this.mb.pop());)ea(f)};c.prototype.Ya=function(){this.freemem();var f=0===Cc(this.Pa);delete this.db.gb[this.Pa];this.Pa=0;return f};d.prototype.next=function(){if(null===this.fb)return{done:!0};null!==this.$a&&(this.$a.Ya(),this.$a=null);
if(!this.db.db)throw this.ob(),Error("Database closed");var f=qa(),l=y(4);ra(g);ra(l);try{this.db.handleError(rb(this.db.db,this.lb,-1,g,l));this.lb=r(l,"i32");var n=r(g,"i32");if(0===n)return this.ob(),{done:!0};this.$a=new c(n,this.db);this.db.gb[n]=this.$a;return{value:this.$a,done:!1}}catch(p){throw this.sb=z(this.lb),this.ob(),p;}finally{ta(f)}};d.prototype.ob=function(){ea(this.fb);this.fb=null};d.prototype.Rb=function(){return null!==this.sb?this.sb:z(this.lb)};"function"===typeof Symbol&&
"symbol"===typeof Symbol.iterator&&(d.prototype[Symbol.iterator]=function(){return this});e.prototype.run=function(f,l){if(!this.db)throw"Database closed";if(l){f=this.tb(f,l);try{f.step()}finally{f.Ya()}}else this.handleError(t(this.db,f,0,0,g));return this};e.prototype.exec=function(f,l,n){if(!this.db)throw"Database closed";var p=null,u=null,w=null;try{w=u=fa(f);var K=y(4);for(f=[];0!==r(w,"i8");){ra(g);ra(K);this.handleError(rb(this.db,w,-1,g,K));var I=r(g,"i32");w=r(K,"i32");if(0!==I){var H=null;
p=new c(I,this);for(null!=l&&p.bind(l);p.step();)null===H&&(H={columns:p.qb(),values:[]},f.push(H)),H.values.push(p.get(null,n));p.Ya()}}return f}catch(L){throw p&&p.Ya(),L;}finally{u&&ea(u)}};e.prototype.Mb=function(f,l,n,p,u){"function"===typeof l&&(p=n,n=l,l=void 0);f=this.tb(f,l);try{for(;f.step();)n(f.zb(null,u))}finally{f.Ya()}if("function"===typeof p)return p()};e.prototype.tb=function(f,l){ra(g);this.handleError(D(this.db,f,-1,g,0));f=r(g,"i32");if(0===f)throw"Nothing to prepare";var n=new c(f,
this);null!=l&&n.bind(l);return this.gb[f]=n};e.prototype.Vb=function(f){return new d(f,this)};e.prototype.Ob=function(){Object.values(this.gb).forEach(function(l){l.Ya()});Object.values(this.Ra).forEach(A);this.Ra={};this.handleError(v(this.db));var f=ua(this.filename);this.handleError(q(this.filename,g));this.db=r(g,"i32");pb(this.db);return f};e.prototype.close=function(){null!==this.db&&(Object.values(this.gb).forEach(function(f){f.Ya()}),Object.values(this.Ra).forEach(A),this.Ra={},this.Za&&
(A(this.Za),this.Za=void 0),this.handleError(v(this.db)),va("/"+this.filename),this.db=null)};e.prototype.handleError=function(f){if(0===f)return null;f=sc(this.db);throw Error(f);};e.prototype.Sb=function(){return x(this.db)};e.prototype.Kb=function(f,l){Object.prototype.hasOwnProperty.call(this.Ra,f)&&(A(this.Ra[f]),delete this.Ra[f]);var n=wa(function(p,u,w){u=b(u,w);try{var K=l.apply(null,u)}catch(I){sa(p,I,-1);return}a(p,K)},"viii");this.Ra[f]=n;this.handleError(ub(this.db,f,l.length,1,0,n,0,
0,0));return this};e.prototype.Jb=function(f,l){var n=l.init||function(){return null},p=l.finalize||function(H){return H},u=l.step;if(!u)throw"An aggregate function must have a step function in "+f;var w={};Object.hasOwnProperty.call(this.Ra,f)&&(A(this.Ra[f]),delete this.Ra[f]);l=f+"__finalize";Object.hasOwnProperty.call(this.Ra,l)&&(A(this.Ra[l]),delete this.Ra[l]);var K=wa(function(H,L,Pa){var V=vb(H,1);Object.hasOwnProperty.call(w,V)||(w[V]=n());L=b(L,Pa);L=[w[V]].concat(L);try{w[V]=u.apply(null,
L)}catch(Ec){delete w[V],sa(H,Ec,-1)}},"viii"),I=wa(function(H){var L=vb(H,1);try{var Pa=p(w[L])}catch(V){delete w[L];sa(H,V,-1);return}a(H,Pa);delete w[L]},"vi");this.Ra[f]=K;this.Ra[l]=I;this.handleError(ub(this.db,f,u.length-1,1,0,0,K,I,0));return this};e.prototype.$b=function(f){this.Za&&(wb(this.db,0,0),A(this.Za),this.Za=void 0);if(!f)return this;this.Za=wa(function(l,n,p,u,w){switch(n){case 18:l="insert";break;case 23:l="update";break;case 9:l="delete";break;default:throw"unknown operationCode in updateHook callback: "+
n;}p=z(p);u=z(u);if(w>Number.MAX_SAFE_INTEGER)throw"rowId too big to fit inside a Number";f(l,p,u,Number(w))},"viiiij");wb(this.db,this.Za,0);return this};c.prototype.bind=c.prototype.bind;c.prototype.step=c.prototype.step;c.prototype.get=c.prototype.get;c.prototype.getColumnNames=c.prototype.qb;c.prototype.getAsObject=c.prototype.zb;c.prototype.getSQL=c.prototype.Tb;c.prototype.getNormalizedSQL=c.prototype.Qb;c.prototype.run=c.prototype.run;c.prototype.reset=c.prototype.reset;c.prototype.freemem=
c.prototype.freemem;c.prototype.free=c.prototype.Ya;d.prototype.next=d.prototype.next;d.prototype.getRemainingSQL=d.prototype.Rb;e.prototype.run=e.prototype.run;e.prototype.exec=e.prototype.exec;e.prototype.each=e.prototype.Mb;e.prototype.prepare=e.prototype.tb;e.prototype.iterateStatements=e.prototype.Vb;e.prototype["export"]=e.prototype.Ob;e.prototype.close=e.prototype.close;e.prototype.handleError=e.prototype.handleError;e.prototype.getRowsModified=e.prototype.Sb;e.prototype.create_function=e.prototype.Kb;
e.prototype.create_aggregate=e.prototype.Jb;e.prototype.updateHook=e.prototype.$b;k.Database=e};var xa="./this.program",ya=(a,b)=>{throw b;},za=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?za=__filename:ba&&(za=self.location.href);var Aa="",Ba,Ca;
if(ca){var fs=require("node:fs");Aa=__dirname+"/";Ca=a=>{a=Da(a)?new URL(a):a;return fs.readFileSync(a)};Ba=async a=>{a=Da(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(xa=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);ya=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{Aa=(new URL(".",za)).href}catch{}ba&&(Ca=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
Ba=async a=>{if(Da(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var Ea=console.log.bind(console),B=console.error.bind(console),Fa,Ga=!1,Ha,Da=a=>a.startsWith("file://");
function Ia(){var a=Ja.buffer;m=new Int8Array(a);Ka=new Int16Array(a);C=new Uint8Array(a);new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);La=new Float32Array(a);Ma=new Float64Array(a);G=new BigInt64Array(a);new BigUint64Array(a)}function Na(a){k.onAbort?.(a);a=`Aborted(${a})`;B(a);Ga=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Oa;
async function Qa(a){if(!Fa)try{var b=await Ba(a);return new Uint8Array(b)}catch{}if(a==Oa&&Fa)a=new Uint8Array(Fa);else if(Ca)a=Ca(a);else throw"both async and sync fetching of the wasm failed";return a}async function Ra(a,b){try{var c=await Qa(a);return await WebAssembly.instantiate(c,b)}catch(d){B(`failed to asynchronously prepare wasm: ${d}`),Na(d)}}
async function Sa(a){var b=Oa;if(!Fa&&!Da(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){B(`wasm streaming compile failed: ${d}`),B("falling back to ArrayBuffer instantiation")}return Ra(b,a)}class Ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ka,E,G,m,La,Ma,F,C,Ua=a=>{for(;0<a.length;)a.shift()(k)},Va=[],Wa=[],Xa=()=>{var a=k.preRun.shift();Wa.push(a)},J=0,Ya=null;
function r(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return m[a];case "i8":return m[a];case "i16":return Ka[a>>1];case "i32":return E[a>>2];case "i64":return G[a>>3];case "float":return La[a>>2];case "double":return Ma[a>>3];case "*":return F[a>>2];default:Na(`invalid type for getValue: ${b}`)}}var Za=!0;
function ra(a){var b="i32";b.endsWith("*")&&(b="*");switch(b){case "i1":m[a]=0;break;case "i8":m[a]=0;break;case "i16":Ka[a>>1]=0;break;case "i32":E[a>>2]=0;break;case "i64":G[a>>3]=BigInt(0);break;case "float":La[a>>2]=0;break;case "double":Ma[a>>3]=0;break;case "*":F[a>>2]=0;break;default:Na(`invalid type for setValue: ${b}`)}}
var $a=new TextDecoder,ab=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},z=(a,b,c)=>a?$a.decode(C.subarray(a,ab(C,a,b,c))):"",bb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ia=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=bb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},cb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},db=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],eb=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},fb=a=>(fb=eb())(a),gb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=bb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":
"")+b||"."},hb=a=>{var b=ab(a,0);return $a.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},ib=[],jb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},M=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|
h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},la=a=>{var b=Array(jb(a)+1);a=M(a,b,0,b.length);b.length=a;return b},kb=[];function mb(a,b){kb[a]={input:[],output:[],eb:b};nb(a,ob)}
var ob={open(a){var b=kb[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close(a){a.tty.eb.fsync(a.tty)},fsync(a){a.tty.eb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.eb.Bb)throw new N(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.eb.Bb(a.tty)}catch(q){throw new N(29);}if(void 0===h&&0===e)throw new N(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.eb.ub)throw new N(60);try{for(var e=0;e<d;e++)a.tty.eb.ub(a.tty,b[c+e])}catch(g){throw new N(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},xb={Bb(){a:{if(!ib.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ib=la(a)}a=ib.shift()}return a},ub(a,b){null===b||10===b?(Ea(hb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(Ea(hb(a.output)),a.output=[])},hc(){return{cc:25856,ec:5,bc:191,dc:35387,ac:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ic(){return 0},jc(){return[24,80]}},yb={ub(a,b){null===b||10===b?(B(hb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(B(hb(a.output)),a.output=[])}},O={Wa:null,Xa(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.Wa||(O.Wa={dir:{node:{Ta:O.La.Ta,
Ua:O.La.Ua,lookup:O.La.lookup,ib:O.La.ib,rename:O.La.rename,unlink:O.La.unlink,rmdir:O.La.rmdir,readdir:O.La.readdir,symlink:O.La.symlink},stream:{Va:O.Ma.Va}},file:{node:{Ta:O.La.Ta,Ua:O.La.Ua},stream:{Va:O.Ma.Va,read:O.Ma.read,write:O.Ma.write,jb:O.Ma.jb,kb:O.Ma.kb}},link:{node:{Ta:O.La.Ta,Ua:O.La.Ua,readlink:O.La.readlink},stream:{}},yb:{node:{Ta:O.La.Ta,Ua:O.La.Ua},stream:zb}});c=Ab(a,b,c,d);P(c.mode)?(c.La=O.Wa.dir.node,c.Ma=O.Wa.dir.stream,c.Qa={}):32768===(c.mode&61440)?(c.La=O.Wa.file.node,
c.Ma=O.Wa.file.stream,c.Sa=0,c.Qa=O.Nb??(O.Nb=new Uint8Array(0))):40960===(c.mode&61440)?(c.La=O.Wa.link.node,c.Ma=O.Wa.link.stream):8192===(c.mode&61440)&&(c.La=O.Wa.yb.node,c.Ma=O.Wa.yb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Qa[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},La:{Ta(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Sa:40960===(a.mode&61440)?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ua(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Sa!=b&&(c=a.Qa,a.Qa=new Uint8Array(b),a.Qa.set(c.subarray(0,Math.min(b,a.Sa))),a.Sa=b))},lookup(){O.nb||(O.nb=new N(44),O.nb.stack="<generic error, no stack>");throw O.nb;},ib(a,b,c,d){return O.createNode(a,b,c,d)},rename(a,b,c){try{var d=Q(b,c)}catch(g){}if(d){if(P(a.mode))for(var e in d.Qa)throw new N(55);
Bb(d)}delete a.parent.Qa[a.name];b.Qa[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Qa[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Q(a,b),d;for(d in c.Qa)throw new N(55);delete a.Qa[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Qa)]},symlink(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},Ma:{read(a,b,c,d,e){if(e>=a.node.Sa)return 0;d=Math.min(a.node.Sa-
e,d);b.set(a.node.Qa.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){b.buffer===m.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(g)a.Qa=b.subarray(c,c+d),a.Sa=d;else if(0===a.Sa&&0===e)a.Qa=b.slice(c,c+d),a.Sa=d;else{g=e+d;var h=a.Qa.length;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),h&&(g=Math.max(g,256)),h=a.Qa.subarray(0,a.Sa),a.Qa=new Uint8Array(g),a.Qa.set(h));a.Qa.set(b.subarray(c,c+d),e);a.Sa=Math.max(a.Sa,e+d)}return d},Va(a,b,c){1===c?b+=a.position:2===c&&32768===
(a.node.mode&61440)&&(b+=a.node.Sa);if(0>b)throw new N(28);return b},jb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.Qa;if(e&2||a.buffer!==m.buffer){e=!0;d=65536*Math.ceil(b/65536);var g=Cb(65536,d);g&&C.fill(0,g,g+d);d=g;if(!d)throw new N(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,d)}}else e=!1,d=a.byteOffset;return{Yb:d,Eb:e}},kb(a,b,c,d){O.Ma.write(a,b,0,d,c,!1);return 0}}},ja=(a,b)=>{var c=0;a&&(c|=365);b&&
(c|=146);return c},Db=null,Eb={},Fb=[],Gb=1,R=null,Hb=!1,Ib=!0,N=class{name="ErrnoError";constructor(a){this.Oa=a}},Jb=class{hb={};node=null;get flags(){return this.hb.flags}set flags(a){this.hb.flags=a}get position(){return this.hb.position}set position(a){this.hb.position=a}},Kb=class{La={};Ma={};bb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Xa=a.Xa;this.id=Gb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function S(a,b={}){if(!a)throw new N(44);b.pb??(b.pb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(q=>!!q);for(var d=Db,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=cb(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=ia(e+"/"+a[g]);try{d=Q(d,a[g])}catch(q){if(44===q?.Oa&&h&&b.Xb)return{path:e};throw q;}!d.bb||h&&!b.pb||(d=d.bb.root);if(40960===(d.mode&61440)&&(!h||b.ab)){if(!d.La.readlink)throw new N(52);
d=d.La.readlink(d);"/"===d.charAt(0)||(d=cb(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new N(32);}function ha(a){for(var b;;){if(a===a.parent)return a=a.Xa.Db,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}
function Bb(a){var b=Lb(a.parent.id,a.name);if(R[b]===a)R[b]=a.cb;else for(b=R[b];b;){if(b.cb===a){b.cb=a.cb;break}b=b.cb}}function Q(a,b){var c=P(a.mode)?(c=Mb(a,"x"))?c:a.La.lookup?0:2:54;if(c)throw new N(c);for(c=R[Lb(a.id,b)];c;c=c.cb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.La.lookup(a,b)}function Ab(a,b,c,d){a=new Kb(a,b,c,d);b=Lb(a.parent.id,a.name);a.cb=R[b];return R[b]=a}function P(a){return 16384===(a&61440)}
function Mb(a,b){return Ib?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function Nb(a,b){if(!P(a.mode))return 54;try{return Q(a,b),20}catch(c){}return Mb(a,"wx")}function Ob(a,b,c){try{var d=Q(a,b)}catch(e){return e.Oa}if(a=Mb(a,"wx"))return a;if(c){if(!P(d.mode))return 54;if(d===d.parent||"/"===ha(d))return 10}else if(P(d.mode))return 31;return 0}function Pb(a){if(!a)throw new N(63);return a}
function T(a){a=Fb[a];if(!a)throw new N(8);return a}function Qb(a,b=-1){a=Object.assign(new Jb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Fb[b])break a;throw new N(33);}a.fd=b;return Fb[b]=a}function Rb(a,b=-1){a=Qb(a,b);a.Ma?.fc?.(a);return a}function Sb(a,b,c){var d=a?.Ma.Ua;a=d?a:b;d??=b.La.Ua;Pb(d);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new N(22);throw e;}}var zb={open(a){a.Ma=Eb[a.node.rdev].Ma;a.Ma.open?.(a)},Va(){throw new N(70);}};function nb(a,b){Eb[a]={Ma:b}}
function Tb(a,b){var c="/"===b;if(c&&Db)throw new N(10);if(!c&&b){var d=S(b,{pb:!1});b=d.path;d=d.node;if(d.bb)throw new N(10);if(!P(d.mode))throw new N(54);}b={type:a,kc:{},Db:b,Wb:[]};a=a.Xa(b);a.Xa=b;b.root=a;c?Db=a:d&&(d.bb=b,d.Xa&&d.Xa.Wb.push(b))}function Ub(a,b,c){var d=S(a,{parent:!0}).node;a=db(a);if(!a)throw new N(28);if("."===a||".."===a)throw new N(20);var e=Nb(d,a);if(e)throw new N(e);if(!d.La.ib)throw new N(63);return d.La.ib(d,a,b,c)}
function ka(a,b=438){return Ub(a,b&4095|32768,0)}function U(a,b=511){return Ub(a,b&1023|16384,0)}function Vb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Ub(a,b|8192,c)}function Wb(a,b){if(!gb(a))throw new N(44);var c=S(b,{parent:!0}).node;if(!c)throw new N(44);b=db(b);var d=Nb(c,b);if(d)throw new N(d);if(!c.La.symlink)throw new N(63);c.La.symlink(c,b,a)}
function Xb(a){var b=S(a,{parent:!0}).node;a=db(a);var c=Q(b,a),d=Ob(b,a,!0);if(d)throw new N(d);if(!b.La.rmdir)throw new N(63);if(c.bb)throw new N(10);b.La.rmdir(b,a);Bb(c)}function va(a){var b=S(a,{parent:!0}).node;if(!b)throw new N(44);a=db(a);var c=Q(b,a),d=Ob(b,a,!1);if(d)throw new N(d);if(!b.La.unlink)throw new N(63);if(c.bb)throw new N(10);b.La.unlink(b,a);Bb(c)}function Yb(a,b){a=S(a,{ab:!b}).node;return Pb(a.La.Ta)(a)}
function Zb(a,b,c,d){Sb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Lb:d})}function ma(a,b){a="string"==typeof a?S(a,{ab:!0}).node:a;Zb(null,a,b)}function $b(a,b,c){if(P(b.mode))throw new N(31);if(32768!==(b.mode&61440))throw new N(28);var d=Mb(b,"w");if(d)throw new N(d);Sb(a,b,{size:c,timestamp:Date.now()})}
function na(a,b,c=438){if(""===a)throw new N(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var g=S(a,{ab:!(b&131072),Xb:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new N(20);}else{if(e)throw new N(31);d=Ub(a,c|511,0);g=!0}if(!d)throw new N(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!P(d.mode))throw new N(54);
if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=P(d.mode)&&("r"!==e||b&576)?31:Mb(d,e)):e=44,e))throw new N(e);b&512&&!g&&(e=d,e="string"==typeof e?S(e,{ab:!0}).node:e,$b(null,e,0));b=Qb({node:d,path:ha(d),flags:b&-131713,seekable:!0,position:0,Ma:d.Ma,Zb:[],error:!1});b.Ma.open&&b.Ma.open(b);g&&ma(d,c&511);return b}function pa(a){if(null===a.fd)throw new N(8);a.rb&&(a.rb=null);try{a.Ma.close&&a.Ma.close(a)}catch(b){throw b;}finally{Fb[a.fd]=null}a.fd=null}
function ac(a,b,c){if(null===a.fd)throw new N(8);if(!a.seekable||!a.Ma.Va)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.Ma.Va(a,b,c);a.Zb=[]}function bc(a,b,c,d,e){if(0>d||0>e)throw new N(28);if(null===a.fd)throw new N(8);if(1===(a.flags&2097155))throw new N(8);if(P(a.node.mode))throw new N(31);if(!a.Ma.read)throw new N(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new N(70);b=a.Ma.read(a,b,c,d,e);g||(a.position+=b);return b}
function oa(a,b,c,d,e){if(0>d||0>e)throw new N(28);if(null===a.fd)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(P(a.node.mode))throw new N(31);if(!a.Ma.write)throw new N(28);a.seekable&&a.flags&1024&&ac(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new N(70);b=a.Ma.write(a,b,c,d,e,void 0);g||(a.position+=b);return b}
function ua(a){var b=b||0;var c="binary";"utf8"!==c&&"binary"!==c&&Na(`Invalid encoding type "${c}"`);b=na(a,b);a=Yb(a).size;var d=new Uint8Array(a);bc(b,d,0,a,0);"utf8"===c&&(d=hb(d));pa(b);return d}
function W(a,b,c){a=ia("/dev/"+a);var d=ja(!!b,!!c);W.Cb??(W.Cb=64);var e=W.Cb++<<8|0;nb(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,h,q,v){for(var t=0,x=0;x<v;x++){try{var D=b()}catch(qb){throw new N(29);}if(void 0===D&&0===t)throw new N(6);if(null===D||void 0===D)break;t++;h[q+x]=D}t&&(g.node.atime=Date.now());return t},write(g,h,q,v){for(var t=0;t<v;t++)try{c(h[q+t])}catch(x){throw new N(29);}v&&(g.node.mtime=g.node.ctime=Date.now());return t}});Vb(a,d,e)}var X={};
function Y(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":T(a).path;if(0==b.length){if(!c)throw new N(44);return a}return a+"/"+b}
function lc(a,b){F[a>>2]=b.dev;F[a+4>>2]=b.mode;F[a+8>>2]=b.nlink;F[a+12>>2]=b.uid;F[a+16>>2]=b.gid;F[a+20>>2]=b.rdev;G[a+24>>3]=BigInt(b.size);E[a+32>>2]=4096;E[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();G[a+40>>3]=BigInt(Math.floor(c/1E3));F[a+48>>2]=c%1E3*1E6;G[a+56>>3]=BigInt(Math.floor(d/1E3));F[a+64>>2]=d%1E3*1E6;G[a+72>>3]=BigInt(Math.floor(e/1E3));F[a+80>>2]=e%1E3*1E6;G[a+88>>3]=BigInt(b.ino);return 0}
var Dc=void 0,Fc=()=>{var a=E[+Dc>>2];Dc+=4;return a},Gc=0,Hc=[0,31,60,91,121,152,182,213,244,274,305,335],Ic=[0,31,59,90,120,151,181,212,243,273,304,334],Jc={},Kc=a=>{Ha=a;Za||0<Gc||(k.onExit?.(a),Ga=!0);ya(a,new Ta(a))},Lc=a=>{if(!Ga)try{a()}catch(b){b instanceof Ta||"unwind"==b||ya(1,b)}finally{if(!(Za||0<Gc))try{Ha=a=Ha,Kc(a)}catch(b){b instanceof Ta||"unwind"==b||ya(1,b)}}},Mc={},Oc=()=>{if(!Nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??
"C").replace("-","_")+".UTF-8",_:xa||"./this.program"},b;for(b in Mc)void 0===Mc[b]?delete a[b]:a[b]=Mc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nc=c}return Nc},Nc,Pc=(a,b,c,d)=>{var e={string:t=>{var x=0;if(null!==t&&void 0!==t&&0!==t){x=jb(t)+1;var D=y(x);M(t,C,D,x);x=D}return x},array:t=>{var x=y(t.length);m.set(t,x);return x}};a=k["_"+a];var g=[],h=0;if(d)for(var q=0;q<d.length;q++){var v=e[c[q]];v?(0===h&&(h=qa()),g[q]=v(d[q])):g[q]=d[q]}c=a(...g);return c=function(t){0!==h&&ta(h);return"string"===
b?z(t):"boolean"===b?!!t:t}(c)},fa=a=>{var b=jb(a)+1,c=da(b);c&&M(a,C,c,b);return c},Qc,Rc=[],A=a=>{Qc.delete(Z.get(a));Z.set(a,null);Rc.push(a)},Sc=a=>{const b=a.length;return[b%128|128,b>>7,...a]},Tc={i:127,p:127,j:126,f:125,d:124,e:111},Uc=a=>Sc(Array.from(a,b=>Tc[b])),wa=(a,b)=>{if(!Qc){Qc=new WeakMap;var c=Z.length;if(Qc)for(var d=0;d<0+c;d++){var e=Z.get(d);e&&Qc.set(e,d)}}if(c=Qc.get(a)||0)return c;c=Rc.length?Rc.pop():Z.grow(1);try{Z.set(c,a)}catch(g){if(!(g instanceof TypeError))throw g;
b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...Sc([1,96,...Uc(b.slice(1)),...Uc("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;Z.set(c,b)}Qc.set(a,c);return c};R=Array(4096);Tb(O,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");nb(259,{read:()=>0,write:(d,e,g,h)=>h,Va:()=>0});Vb("/dev/null",259);mb(1280,xb);mb(1536,yb);Vb("/dev/tty",1280);Vb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(fb(a),b=a.byteLength);return a[--b]};W("random",c);W("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");Tb({Xa(){var b=Ab(a,"fd",16895,73);b.Ma={Va:O.Ma.Va};b.La={lookup(c,d){c=+d;var e=T(c);c={parent:null,Xa:{Db:"fake"},La:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(Fb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k.noExitRuntime&&(Za=k.noExitRuntime);k.print&&(Ea=k.print);k.printErr&&(B=k.printErr);k.wasmBinary&&(Fa=k.wasmBinary);k.thisProgram&&(xa=k.thisProgram);
if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();k.stackSave=()=>qa();k.stackRestore=a=>ta(a);k.stackAlloc=a=>y(a);k.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?k["_"+a]:(...g)=>Pc(a,b,c,g)};k.addFunction=wa;k.removeFunction=A;k.UTF8ToString=z;k.stringToNewUTF8=fa;k.writeArrayToMemory=(a,b)=>{m.set(a,b)};
var da,ea,Cb,Vc,ta,y,qa,Ja,Z,Wc={a:(a,b,c,d)=>Na(`Assertion failed: ${z(a)}, at: `+[b?z(b):"unknown filename",c,d?z(d):"unknown function"]),i:function(a,b){try{return a=z(a),ma(a,b),0}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return-c.Oa}},L:function(a,b,c){try{b=z(b);b=Y(a,b);if(c&-8)return-28;var d=S(b,{ab:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Mb(d,a)?-2:0}catch(e){if("undefined"==typeof X||"ErrnoError"!==e.name)throw e;return-e.Oa}},
j:function(a,b){try{var c=T(a);Zb(c,c.node,b,!1);return 0}catch(d){if("undefined"==typeof X||"ErrnoError"!==d.name)throw d;return-d.Oa}},h:function(a){try{var b=T(a);Sb(b,b.node,{timestamp:Date.now(),Lb:!1});return 0}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return-c.Oa}},b:function(a,b,c){Dc=c;try{var d=T(a);switch(b){case 0:var e=Fc();if(0>e)break;for(;Fb[e];)e++;return Rb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Fc(),d.flags=d.flags&-289793|e&
289792,0;case 12:return e=Fc(),Ka[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof X||"ErrnoError"!==g.name)throw g;return-g.Oa}},g:function(a,b){try{var c=T(a),d=c.node,e=c.Ma.Ta;a=e?c:d;e??=d.La.Ta;Pb(e);var g=e(a);return lc(b,g)}catch(h){if("undefined"==typeof X||"ErrnoError"!==h.name)throw h;return-h.Oa}},H:function(a,b){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;var c=T(a);if(0>b||0===(c.flags&2097155))throw new N(28);$b(c,
c.node,b);return 0}catch(d){if("undefined"==typeof X||"ErrnoError"!==d.name)throw d;return-d.Oa}},G:function(a,b){try{if(0===b)return-28;var c=jb("/")+1;if(b<c)return-68;M("/",C,a,b);return c}catch(d){if("undefined"==typeof X||"ErrnoError"!==d.name)throw d;return-d.Oa}},K:function(a,b){try{return a=z(a),lc(b,Yb(a,!0))}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return-c.Oa}},C:function(a,b,c){try{return b=z(b),b=Y(a,b),U(b,c&-19),0}catch(d){if("undefined"==typeof X||"ErrnoError"!==
d.name)throw d;return-d.Oa}},J:function(a,b,c,d){try{b=z(b);var e=d&256;b=Y(a,b,d&4096);return lc(c,e?Yb(b,!0):Yb(b))}catch(g){if("undefined"==typeof X||"ErrnoError"!==g.name)throw g;return-g.Oa}},x:function(a,b,c,d){Dc=d;try{b=z(b);b=Y(a,b);var e=d?Fc():0;c&64&&(e&=-19);return na(b,c,e).fd}catch(g){if("undefined"==typeof X||"ErrnoError"!==g.name)throw g;return-g.Oa}},s:function(a,b,c,d){try{b=z(b);b=Y(a,b);if(0>=d)return-28;var e=S(b).node;if(!e)throw new N(44);if(!e.La.readlink)throw new N(28);
var g=e.La.readlink(e);var h=Math.min(d,jb(g)),q=m[c+h];M(g,C,c,d+1);m[c+h]=q;return h}catch(v){if("undefined"==typeof X||"ErrnoError"!==v.name)throw v;return-v.Oa}},r:function(a){try{return a=z(a),Xb(a),0}catch(b){if("undefined"==typeof X||"ErrnoError"!==b.name)throw b;return-b.Oa}},f:function(a,b){try{return a=z(a),lc(b,Yb(a))}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return-c.Oa}},o:function(a,b,c){try{b=z(b);b=Y(a,b);if(c)if(512===c)Xb(b);else return-28;else va(b);return 0}catch(d){if("undefined"==
typeof X||"ErrnoError"!==d.name)throw d;return-d.Oa}},n:function(a,b,c){try{b=z(b);b=Y(a,b,!0);var d=Date.now(),e,g;if(c){var h=F[c>>2]+4294967296*E[c+4>>2],q=E[c+8>>2];1073741823==q?e=d:1073741822==q?e=null:e=1E3*h+q/1E6;c+=16;h=F[c>>2]+4294967296*E[c+4>>2];q=E[c+8>>2];1073741823==q?g=d:1073741822==q?g=null:g=1E3*h+q/1E6}else g=e=d;if(null!==(g??e)){a=e;var v=S(b,{ab:!0}).node;Pb(v.La.Ua)(v,{atime:a,mtime:g})}return 0}catch(t){if("undefined"==typeof X||"ErrnoError"!==t.name)throw t;return-t.Oa}},
w:()=>Na(""),v:()=>{Za=!1;Gc=0},A:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=a.getFullYear();E[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ic:Hc)[a.getMonth()]+a.getDate()-1|0;E[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},y:function(a,b,c,d,e,g,h){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var q=T(d);if(0!==(b&2)&&0===(c&2)&&2!==(q.flags&2097155))throw new N(2);if(1===(q.flags&2097155))throw new N(2);if(!q.Ma.jb)throw new N(43);if(!a)throw new N(28);var v=q.Ma.jb(q,a,e,b,c);var t=v.Yb;E[g>>2]=v.Eb;F[h>>2]=t;return 0}catch(x){if("undefined"==typeof X||"ErrnoError"!==x.name)throw x;return-x.Oa}},z:function(a,b,c,d,e,
g){g=-9007199254740992>g||9007199254740992<g?NaN:Number(g);try{var h=T(e);if(c&2){c=g;if(32768!==(h.node.mode&61440))throw new N(43);if(!(d&2)){var q=C.slice(a,a+b);h.Ma.kb&&h.Ma.kb(h,q,c,b,d)}}}catch(v){if("undefined"==typeof X||"ErrnoError"!==v.name)throw v;return-v.Oa}},k:(a,b)=>{Jc[a]&&(clearTimeout(Jc[a].id),delete Jc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Jc[a];Lc(()=>Vc(a,performance.now()))},b);Jc[a]={id:c,lc:b};return 0},B:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,
0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();F[a>>2]=60*Math.max(g,e);E[b>>2]=Number(g!=e);b=h=>{var q=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(q/60)).padStart(2,"0")}${String(q%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(M(a,C,c,17),M(b,C,d,17)):(M(a,C,d,17),M(b,C,c,17))},d:()=>Date.now(),p:()=>2147483648,c:()=>performance.now(),l:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-Ja.buffer.byteLength+65535)/65536|0;try{Ja.grow(d);Ia();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},E:(a,b)=>{var c=0,d=0,e;for(e of Oc()){var g=b+c;F[a+d>>2]=g;c+=M(e,C,g,Infinity)+1;d+=4}return 0},F:(a,b)=>{var c=Oc();F[a>>2]=c.length;a=0;for(var d of c)a+=jb(d)+1;F[b>>2]=a;return 0},e:function(a){try{var b=T(a);pa(b);return 0}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return c.Oa}},m:function(a,b){try{var c=T(a);m[b]=c.tty?
2:P(c.mode)?3:40960===(c.mode&61440)?7:4;Ka[b+2>>1]=0;G[b+8>>3]=BigInt(0);G[b+16>>3]=BigInt(0);return 0}catch(d){if("undefined"==typeof X||"ErrnoError"!==d.name)throw d;return d.Oa}},t:function(a,b,c,d){try{a:{var e=T(a);a=b;for(var g,h=b=0;h<c;h++){var q=F[a>>2],v=F[a+4>>2];a+=8;var t=bc(e,m,q,v,g);if(0>t){var x=-1;break a}b+=t;if(t<v)break;"undefined"!=typeof g&&(g+=t)}x=b}F[d>>2]=x;return 0}catch(D){if("undefined"==typeof X||"ErrnoError"!==D.name)throw D;return D.Oa}},D:function(a,b,c,d){b=-9007199254740992>
b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=T(a);ac(e,b,c);G[d>>3]=BigInt(e.position);e.rb&&0===b&&0===c&&(e.rb=null);return 0}catch(g){if("undefined"==typeof X||"ErrnoError"!==g.name)throw g;return g.Oa}},I:function(a){try{var b=T(a);return b.Ma?.fsync?.(b)}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return c.Oa}},q:function(a,b,c,d){try{a:{var e=T(a);a=b;for(var g,h=b=0;h<c;h++){var q=F[a>>2],v=F[a+4>>2];a+=8;var t=oa(e,m,q,v,g);if(0>t){var x=-1;break a}b+=
t;if(t<v)break;"undefined"!=typeof g&&(g+=t)}x=b}F[d>>2]=x;return 0}catch(D){if("undefined"==typeof X||"ErrnoError"!==D.name)throw D;return D.Oa}},u:Kc};
function Xc(){function a(){k.calledRun=!0;if(!Ga){if(!k.noFSInit&&!Hb){var b,c;Hb=!0;b??=k.stdin;c??=k.stdout;d??=k.stderr;b?W("stdin",b):Wb("/dev/tty","/dev/stdin");c?W("stdout",null,c):Wb("/dev/tty","/dev/stdout");d?W("stderr",null,d):Wb("/dev/tty1","/dev/stderr");na("/dev/stdin",0);na("/dev/stdout",1);na("/dev/stderr",1)}Yc.N();Ib=!1;k.onRuntimeInitialized?.();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var d=k.postRun.shift();Va.push(d)}Ua(Va)}}if(0<
J)Ya=Xc;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Xa();Ua(Wa);0<J?Ya=Xc:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);a()},1)):a()}}var Yc;
(async function(){function a(c){c=Yc=c.exports;k._sqlite3_free=c.P;k._sqlite3_value_text=c.Q;k._sqlite3_prepare_v2=c.R;k._sqlite3_step=c.S;k._sqlite3_reset=c.T;k._sqlite3_exec=c.U;k._sqlite3_finalize=c.V;k._sqlite3_column_name=c.W;k._sqlite3_column_text=c.X;k._sqlite3_column_type=c.Y;k._sqlite3_errmsg=c.Z;k._sqlite3_clear_bindings=c._;k._sqlite3_value_blob=c.$;k._sqlite3_value_bytes=c.aa;k._sqlite3_value_double=c.ba;k._sqlite3_value_int=c.ca;k._sqlite3_value_type=c.da;k._sqlite3_result_blob=c.ea;
k._sqlite3_result_double=c.fa;k._sqlite3_result_error=c.ga;k._sqlite3_result_int=c.ha;k._sqlite3_result_int64=c.ia;k._sqlite3_result_null=c.ja;k._sqlite3_result_text=c.ka;k._sqlite3_aggregate_context=c.la;k._sqlite3_column_count=c.ma;k._sqlite3_data_count=c.na;k._sqlite3_column_blob=c.oa;k._sqlite3_column_bytes=c.pa;k._sqlite3_column_double=c.qa;k._sqlite3_bind_blob=c.ra;k._sqlite3_bind_double=c.sa;k._sqlite3_bind_int=c.ta;k._sqlite3_bind_text=c.ua;k._sqlite3_bind_parameter_index=c.va;k._sqlite3_sql=
c.wa;k._sqlite3_normalized_sql=c.xa;k._sqlite3_changes=c.ya;k._sqlite3_close_v2=c.za;k._sqlite3_create_function_v2=c.Aa;k._sqlite3_update_hook=c.Ba;k._sqlite3_open=c.Ca;da=k._malloc=c.Da;ea=k._free=c.Ea;k._RegisterExtensionFunctions=c.Fa;Cb=c.Ga;Vc=c.Ha;ta=c.Ia;y=c.Ja;qa=c.Ka;Ja=c.M;Z=c.O;Ia();J--;k.monitorRunDependencies?.(J);0==J&&Ya&&(c=Ya,Ya=null,c());return Yc}J++;k.monitorRunDependencies?.(J);var b={a:Wc};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});
Oa??=k.locateFile?k.locateFile("sql-wasm.wasm",Aa):Aa+"sql-wasm.wasm";return a((await Sa(b)).instance)})();Xc();


        // The shell-pre.js and emcc-generated code goes above
        return Module;
    }); // The end of the promise being returned

  return initSqlJsPromise;
} // The end of our initSqlJs function

// This bit below is copied almost exactly from what you get when you use the MODULARIZE=1 flag with emcc
// However, we don't want to use the emcc modularization. See shell-pre.js
if (typeof exports === 'object' && typeof module === 'object'){
    module.exports = initSqlJs;
    // This will allow the module to be used in ES6 or CommonJS
    module.exports.default = initSqlJs;
}
else if (typeof define === 'function' && define['amd']) {
    define([], function() { return initSqlJs; });
}
else if (typeof exports === 'object'){
    exports["Module"] = initSqlJs;
}
