import { ParsedNote } from '../vault/types';
import { VaultManager } from '../vault/manager';

export interface ContextBlock {
  title: string;
  content: string;
  tokenEstimate: number;
}

export class ContextGenerator {
  constructor(private manager: VaultManager) {}

  /** Compile selected notes into a single context block for AI tools */
  async compileContext(notePaths: string[], options?: {
    includeMetadata?: boolean;
    maxTokens?: number;
    format?: 'markdown' | 'xml';
  }): Promise<string> {
    const opts = {
      includeMetadata: true,
      maxTokens: 4000,
      format: 'markdown' as const,
      ...options,
    };

    const notes = await Promise.all(
      notePaths.map(p => this.manager.readNote(p))
    );

    if (opts.format === 'xml') {
      return this.formatXml(notes, opts);
    }
    return this.formatMarkdown(notes, opts);
  }

  /** Generate active project context — all active/next tasks with their project context */
  async compileActiveContext(): Promise<string> {
    const activeTasks = await this.manager.queryNotes({ type: 'task', status: 'active' });
    const nextTasks = await this.manager.queryNotes({ type: 'task', status: 'next' });
    const allTasks = [...activeTasks, ...nextTasks];

    if (allTasks.length === 0) {
      return '<!-- No active or next tasks found in vault -->';
    }

    const lines: string[] = [
      '# Current Work Context',
      '',
      `_Generated ${new Date().toISOString().slice(0, 16)}_`,
      '',
    ];

    // Group by project
    const byProject = new Map<string, ParsedNote[]>();
    for (const task of allTasks) {
      const project = task.frontmatter.project ?? 'Unassigned';
      if (!byProject.has(project)) byProject.set(project, []);
      byProject.get(project)!.push(task);
    }

    for (const [project, tasks] of byProject) {
      lines.push(`## ${project}`, '');
      for (const task of tasks) {
        const status = task.frontmatter.status ?? 'unknown';
        const title = task.frontmatter.title ?? task.relativePath;
        const scope = task.source === 'workspace' ? '📁' : '🌐';
        const contexts = task.frontmatter.context
          ? ` (${(task.frontmatter.context as string[]).join(', ')})`
          : '';
        lines.push(`- ${scope} **[${status}]** ${title}${contexts}`);

        // Include first paragraph of body as context
        const firstPara = task.body.trim().split('\n\n')[0];
        if (firstPara && firstPara.length < 200) {
          lines.push(`  > ${firstPara}`);
        }
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /** Generate CLAUDE.md content from vault knowledge */
  async generateClaudeMd(projectPath: string): Promise<string> {
    const activeContext = await this.compileActiveContext();
    const referenceDocs = await this.manager.queryNotes({ type: 'reference' });

    const lines: string[] = [
      '# CLAUDE.md',
      '',
      '> Auto-generated by KB Vault. Do not edit directly.',
      '',
      activeContext,
      '',
    ];

    if (referenceDocs.length > 0) {
      lines.push('## Reference Knowledge', '');
      for (const doc of referenceDocs.slice(0, 10)) {
        const title = doc.frontmatter.title ?? doc.relativePath;
        const scope = doc.source === 'workspace' ? '📁' : '🌐';
        lines.push(`### ${scope} ${title}`, '');
        const truncated = doc.body.trim().slice(0, 500);
        lines.push(truncated);
        if (doc.body.trim().length > 500) lines.push('...');
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /** Generate .github/copilot-instructions.md content */
  async generateCopilotInstructions(): Promise<string> {
    const activeContext = await this.compileActiveContext();

    return [
      '# Copilot Instructions',
      '',
      '> Auto-generated by KB Vault. Do not edit directly.',
      '',
      activeContext,
    ].join('\n');
  }

  private formatMarkdown(notes: ParsedNote[], opts: { includeMetadata: boolean }): string {
    const lines: string[] = [
      '# KB Vault Context',
      '',
      `_Compiled ${new Date().toISOString().slice(0, 16)} — ${notes.length} file(s)_`,
      '',
    ];

    for (const note of notes) {
      const title = note.frontmatter.title ?? note.relativePath;
      const scope = note.source === 'workspace' ? '📁' : '🌐';
      lines.push(`## ${scope} ${title}`, '');

      if (opts.includeMetadata) {
        const meta: string[] = [];
        if (note.frontmatter.type) meta.push(`type: ${note.frontmatter.type}`);
        if (note.frontmatter.status) meta.push(`status: ${note.frontmatter.status}`);
        if (note.frontmatter.tags) meta.push(`tags: ${(note.frontmatter.tags as string[]).join(', ')}`);
        if (note.frontmatter.project) meta.push(`project: ${note.frontmatter.project}`);
        if (meta.length) {
          lines.push(`> ${meta.join(' | ')}`, '');
        }
      }

      lines.push(note.body.trim(), '', '---', '');
    }

    return lines.join('\n');
  }

  private formatXml(notes: ParsedNote[], opts: { includeMetadata: boolean }): string {
    const lines: string[] = ['<knowledge-context>'];

    for (const note of notes) {
      const title = note.frontmatter.title ?? note.relativePath;
      lines.push(`  <document title="${escapeXml(title)}" path="${escapeXml(note.relativePath)}" scope="${note.source}">`);

      if (opts.includeMetadata && note.frontmatter.type) {
        lines.push(`    <metadata type="${note.frontmatter.type}" status="${note.frontmatter.status ?? ''}" />`);
      }

      lines.push(`    <content>`);
      lines.push(`      ${escapeXml(note.body.trim())}`);
      lines.push(`    </content>`);
      lines.push(`  </document>`);
    }

    lines.push('</knowledge-context>');
    return lines.join('\n');
  }
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
