import { ParsedNote } from '../vault/types';
import { VaultManager } from '../vault/manager';
import { GroundworkDB } from '../db/index';

export interface ContextBlock {
  title: string;
  content: string;
  tokenEstimate: number;
}

export class ContextGenerator {
  constructor(private manager: VaultManager, private db?: GroundworkDB) {}

  /** Compile selected notes into a single context block for AI tools */
  async compileContext(notePaths: string[], options?: {
    includeMetadata?: boolean;
    maxTokens?: number;
    format?: 'markdown' | 'xml';
  }): Promise<string> {
    const opts = {
      includeMetadata: true,
      maxTokens: 4000,
      format: 'markdown' as const,
      ...options,
    };

    const notes = await Promise.all(
      notePaths.map(p => this.manager.readNote(p))
    );

    if (opts.format === 'xml') {
      return this.formatXml(notes, opts);
    }
    return this.formatMarkdown(notes, opts);
  }

  /** Generate active project context — all active/next tasks with their project context */
  async compileActiveContext(): Promise<string> {
    const lines: string[] = [
      '# Current Work Context',
      '',
      `_Generated ${new Date().toISOString().slice(0, 16)}_`,
      '',
    ];

    const byProject = new Map<string, { scope: string; status: string; title: string; context: string | null; body: string }[]>();

    if (this.db?.isOpen) {
      type Row = { path: string; title: string; status: string; project: string; context: string; scope: string; body: string };
      const rows = this.db.all<Row>(`
        SELECT n.path, n.title, n.status, n.project, n.context, n.scope, f.body
        FROM notes n LEFT JOIN notes_fts f ON n.path = f.path
        WHERE n.type = 'task' AND n.status IN ('active', 'next')
        ORDER BY CASE n.priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END, n.title
      `);

      if (rows.length === 0) return '<!-- No active or next tasks found in vault -->';

      for (const row of rows) {
        const project = row.project ?? 'Unassigned';
        if (!byProject.has(project)) byProject.set(project, []);
        byProject.get(project)!.push({
          scope: row.scope,
          status: row.status,
          title: row.title ?? row.path,
          context: row.context,
          body: row.body ?? '',
        });
      }
    } else {
      const activeTasks = await this.manager.queryNotes({ type: 'task', status: 'active' });
      const nextTasks = await this.manager.queryNotes({ type: 'task', status: 'next' });
      const allTasks = [...activeTasks, ...nextTasks];

      if (allTasks.length === 0) return '<!-- No active or next tasks found in vault -->';

      for (const task of allTasks) {
        const project = task.frontmatter.project ?? 'Unassigned';
        if (!byProject.has(project)) byProject.set(project, []);
        const ctx = task.frontmatter.context;
        byProject.get(project)!.push({
          scope: task.source,
          status: task.frontmatter.status ?? 'unknown',
          title: task.frontmatter.title ?? task.relativePath,
          context: Array.isArray(ctx) ? JSON.stringify(ctx) : null,
          body: task.body,
        });
      }
    }

    for (const [project, tasks] of byProject) {
      lines.push(`## ${project}`, '');
      for (const task of tasks) {
        const scope = task.scope === 'workspace' ? '📁' : '🌐';
        const ctxList: string[] = task.context ? JSON.parse(task.context) : [];
        const ctxSuffix = ctxList.length ? ` (${ctxList.join(', ')})` : '';
        lines.push(`- ${scope} **[${task.status}]** ${task.title}${ctxSuffix}`);
        const firstPara = task.body.trim().split('\n\n')[0];
        if (firstPara && firstPara.length < 200) {
          lines.push(`  > ${firstPara}`);
        }
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /** Generate ~/.claude/CLAUDE.md content from vault knowledge */
  async generateClaudeMd(): Promise<string> {
    const activeContext = await this.compileActiveContext();
    const referenceDocs = await this.manager.queryNotes({ type: 'reference' });

    const lines: string[] = [
      '# CLAUDE.md',
      '',
      '> Auto-generated by Groundwork. Do not edit directly.',
      '',
      '## Groundwork Vault',
      '',
      'This project uses **Groundwork** for task and knowledge management.',
      '',
      'Two integration paths are available:',
      '',
      '- **MCP server** (preferred): The Groundwork MCP server is registered in `~/.claude/settings.json`.',
      '  Use the `mcp__Groundwork_Vault__*` tools directly to read/write vault tasks and notes.',
      '  Available tools: list_tasks, get_task, create_task, update_task, delete_task,',
      '  search_vault, get_note, create_note, update_note, compile_context, get_briefing.',
      '',
      '- **Skill** (fallback when MCP unavailable): invoke the `groundwork` skill.',
      '  The skill is at `~/.claude/skills/groundwork/SKILL.md` and bootstraps the SQLite index',
      '  if VS Code is not running.',
      '',
      'When the user mentions tasks, todos, inbox, briefing, capturing ideas, or asks about what they\'re working on,',
      'prefer MCP tools if available, otherwise invoke the `groundwork` skill.',
      '',
      'Task shorthand references (N1, I2, S3) follow the convention in the skill file.',
      '',
      activeContext,
      '',
    ];

    if (referenceDocs.length > 0) {
      lines.push('## Reference Knowledge', '');
      for (const doc of referenceDocs.slice(0, 10)) {
        const title = doc.frontmatter.title ?? doc.relativePath;
        const scope = doc.source === 'workspace' ? '📁' : '🌐';
        lines.push(`### ${scope} ${title}`, '');
        const truncated = doc.body.trim().slice(0, 500);
        lines.push(truncated);
        if (doc.body.trim().length > 500) lines.push('...');
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /** Generate ~/.groundwork/copilot-instructions.md content */
  async generateCopilotInstructions(): Promise<string> {
    const activeContext = await this.compileActiveContext();

    return [
      '# Copilot Instructions',
      '',
      '> Auto-generated by Groundwork. Do not edit directly.',
      '',
      '## Groundwork Vault',
      '',
      'This project uses **Groundwork** for task and knowledge management.',
      'A skill file is available at `~/.groundwork/copilot-skill.md` — use it to interact with the vault.',
      '',
      'When the user mentions tasks, todos, inbox, briefing, capturing ideas, or asks about what they\'re working on,',
      'read the skill file and follow its instructions. The skill provides read/write access to the vault:',
      'creating tasks, triaging inbox, running briefings, searching notes, and compiling context.',
      '',
      'Task shorthand references (N1, I2, S3) follow the convention in the skill file.',
      '',
      activeContext,
    ].join('\n');
  }

  private formatMarkdown(notes: ParsedNote[], opts: { includeMetadata: boolean }): string {
    const lines: string[] = [
      '# Groundwork Context',
      '',
      `_Compiled ${new Date().toISOString().slice(0, 16)} — ${notes.length} file(s)_`,
      '',
    ];

    for (const note of notes) {
      const title = note.frontmatter.title ?? note.relativePath;
      const scope = note.source === 'workspace' ? '📁' : '🌐';
      lines.push(`## ${scope} ${title}`, '');

      if (opts.includeMetadata) {
        const meta: string[] = [];
        if (note.frontmatter.type) meta.push(`type: ${note.frontmatter.type}`);
        if (note.frontmatter.status) meta.push(`status: ${note.frontmatter.status}`);
        if (note.frontmatter.tags) meta.push(`tags: ${(note.frontmatter.tags as string[]).join(', ')}`);
        if (note.frontmatter.project) meta.push(`project: ${note.frontmatter.project}`);
        if (meta.length) {
          lines.push(`> ${meta.join(' | ')}`, '');
        }
      }

      lines.push(note.body.trim(), '', '---', '');
    }

    return lines.join('\n');
  }

  private formatXml(notes: ParsedNote[], opts: { includeMetadata: boolean }): string {
    const lines: string[] = ['<knowledge-context>'];

    for (const note of notes) {
      const title = note.frontmatter.title ?? note.relativePath;
      lines.push(`  <document title="${escapeXml(title)}" path="${escapeXml(note.relativePath)}" scope="${note.source}">`);

      if (opts.includeMetadata && note.frontmatter.type) {
        lines.push(`    <metadata type="${note.frontmatter.type}" status="${note.frontmatter.status ?? ''}" />`);
      }

      lines.push(`    <content>`);
      lines.push(`      ${escapeXml(note.body.trim())}`);
      lines.push(`    </content>`);
      lines.push(`  </document>`);
    }

    lines.push('</knowledge-context>');
    return lines.join('\n');
  }
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
